name: Terraform CI/CD

on:

  # Feature branch par push hone par CI chalega
  push:
    branches:
      - 'feature/**'
      - main

  # Feature branch se main ke liye PR banne par CI chalega
  pull_request:
    branches:
      - main

  # Manual run
  workflow_dispatch:

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Azure Login
        uses: azure/login@v2
        with:
        AZURE_CLIENT_ID: ${{ secrets.23d94bc9-72f3-4625-809a-f3e550b86c97 }}
        AZURE_CLIENT_SECRET: ${{ secrets.XWk8Q~Bd2rvBbvt92PYVAZqGYtlxGtVjWoq3tcpq }}
        AZURE_TENANT_ID: ${{ secrets.d7017306-79d9-4de7-8812-4ffebec6d3ba }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.7d2b7ec8-30a6-4bc2-9251-5eb16f970054 }} 

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan


  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    # Only run after code is pushed/merged to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
